#!/bin/bash

# Slackware build script for cabal-dev

PRGNAM=cabal-dev
VERSION=${VERSION:-$(cabal install -v0 --dry-run cabal-dev | tail -1 | sed -ne 's/^.*-\([0-9.]\+\).*$/\1/p')}
BUILD=${BUILD:-1}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i486 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

CWD=$(pwd)
TMP=${TMP:-/tmp}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i486" ]; then
  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
rm -rf $PRGNAM-$VERSION
mkdir $PRGNAM-$VERSION
cd $PRGNAM-$VERSION

# chown -R root:root .
# find . \
#  \( -perm 777 -o -perm 775 -o -perm 711 -o -perm 555 -o -perm 511 \) \
#  -exec chmod 755 {} \; -o \
#  \( -perm 666 -o -perm 664 -o -perm 600 -o -perm 444 -o -perm 440 -o -perm 400 \) \
#  -exec chmod 644 {} \;

PACKAGE_DB="$(pwd)/cabal/package-conf.d"

git clone git://github.com/creswick/cabal-dev.git
cd cabal-dev
ghc-pkg init $PACKAGE_DB


for str in $(cabal install --dry-run | tail +3 | grep -v cabal-dev | cut -d' ' -f1); do
    wget http://hackage.haskell.org/packages/archive/$(echo $str | sed -ne 's/^\([^ ]\+\)-\([0-9\.]\+\).*$/\1\/\2/p')/$str.tar.gz
    tar xvf $str.tar.gz
    ( cd $str
    cabal configure \
        --package-db=$PACKAGE_DB \
        --enable-split-objs \
        --prefix=$TMP/$PRGNAM-$VERSION/cabal
    cabal build
    cabal install \
        --force-reinstall \
        --prefix=$TMP/$PRGNAM-$VERSION/cabal \
        --package-db=$PACKAGE_DB
    )
done

# wget http://hackage.haskell.org/packages/archive/$PRGNAM/$VERSION/$PRGNAM-$VERSION.tar.gz
# tar xvf $PRGNAM-$VERSION.tar.gz
# cd $PRGNAM-$VERSION

CFLAGS="$SLKCFLAGS" \
CXXFLAGS="$SLKCFLAGS" \
cabal configure \
    --prefix=/usr \
    --docdir=/usr/doc/$PRGNAM-$VERSION \
    --package-db=$PACKAGE_DB \
    --enable-split-objs


cabal build
cabal copy --destdir=$PKG

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true

mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild

mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-tgz}
